export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>Archive</title>
  <base href="https://jesse-rr.github.io/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>*,*:before,*:after{box-sizing:border-box;margin:0;padding:0}:root{--bg: #f5f5f7;--text: #1a1a1a;--text-muted: #888;--header-bg: rgba(245, 245, 247, .85);--border: rgba(0, 0, 0, .08);--accent: #5856d6;--btn-bg: rgba(0, 0, 0, .04);--btn-color: #1a1a1a;--btn-border: rgba(0, 0, 0, .1);--btn-hover: rgba(0, 0, 0, .08);--folder-tab: #4a4a4f;--folder-body: #5a5a60;--folder-text: #e0e0e0;--folder-placeholder: #3a3a3f;--theme-btn-bg: rgba(0, 0, 0, .06);--theme-btn-hover: rgba(0, 0, 0, .12)}body{background:var(--bg);color:var(--text);font-family:Inter,-apple-system,BlinkMacSystemFont,sans-serif;min-height:100dvh;transition:background .3s,color .3s}
</style><link rel="stylesheet" href="styles-GQRM7QDT.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-GQRM7QDT.css"></noscript><style ng-app-id="ng">.home[_ngcontent-ng-c2307554362]{padding:24px 32px;min-height:calc(100dvh - 60px)}.toolbar[_ngcontent-ng-c2307554362]{display:flex;align-items:center;gap:16px;margin-bottom:32px;flex-wrap:wrap}.categories[_ngcontent-ng-c2307554362]{display:flex;gap:8px;flex-wrap:wrap}.cat-btn[_ngcontent-ng-c2307554362]{background:var(--btn-bg);color:var(--btn-color);border:1px solid var(--btn-border);border-radius:20px;padding:6px 16px;font-size:.85rem;cursor:pointer;transition:background .2s,color .2s,border-color .2s}.cat-btn[_ngcontent-ng-c2307554362]:hover{background:var(--btn-hover);border-color:var(--accent)}.cat-btn.active[_ngcontent-ng-c2307554362]{background:var(--accent);color:#fff;border-color:var(--accent)}.search[_ngcontent-ng-c2307554362]{flex:1;min-width:200px;max-width:400px;padding:8px 16px;border-radius:20px;border:1px solid var(--btn-border);background:var(--btn-bg);color:var(--text);font-size:.9rem;outline:none;transition:border-color .2s}.search[_ngcontent-ng-c2307554362]::placeholder{color:var(--text-muted)}.search[_ngcontent-ng-c2307554362]:focus{border-color:var(--accent)}.grid[_ngcontent-ng-c2307554362]{display:grid;grid-template-columns:repeat(5,1fr);gap:20px}@media (max-width: 1200px){.grid[_ngcontent-ng-c2307554362]{grid-template-columns:repeat(4,1fr)}}@media (max-width: 900px){.grid[_ngcontent-ng-c2307554362]{grid-template-columns:repeat(3,1fr)}}@media (max-width: 600px){.grid[_ngcontent-ng-c2307554362]{grid-template-columns:repeat(2,1fr)}}.empty[_ngcontent-ng-c2307554362]{grid-column:1/-1;text-align:center;color:var(--text-muted);padding:60px 0;font-size:1rem}</style><style ng-app-id="ng">.header[_ngcontent-ng-c1547807914]{display:flex;align-items:center;justify-content:space-between;padding:0 32px;height:60px;background:var(--header-bg);border-bottom:1px solid var(--border);position:sticky;top:0;z-index:100;backdrop-filter:blur(10px)}.logo[_ngcontent-ng-c1547807914]{font-size:1.2rem;font-weight:700;letter-spacing:.05em;color:var(--text)}</style><style ng-app-id="ng">.theme-toggle[_ngcontent-ng-c309322150]{background:var(--theme-btn-bg);color:var(--text);border:none;border-radius:8px;padding:6px 14px;font-size:.85rem;font-weight:500;cursor:pointer;transition:background .2s}.theme-toggle[_ngcontent-ng-c309322150]:hover{background:var(--theme-btn-hover)}</style></head>
<body><!--nghm-->
  <app-root ng-version="19.2.20" ngh="0" ng-server-context="ssg"><router-outlet></router-outlet><!----></app-root>
<script src="polyfills-B6TNHZQ6.js" type="module"></script><script src="main-BBSL2GLX.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"c":{"0":[]}}]}</script></body></html>`;